name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t newmohib/nodejs-graphql-app .
      - name: Publish image to docker hub
        run: docker push newmohib/nodejs-graphql-app:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull newmohib/nodejs-graphql-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-graphql-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-graphql-app-container newmohib/nodejs-graphql-app
